import base64 # ha sa 

encoded_data = "0U7Sk0SmeTmTpa2TmzRkzpgYmiuPmvlRpOmMSASSmLSmuOmcSmVogCyRgPm8obsOmUKm9Ej4RmQKclOmHzIQSmsaUcSkhAMpSm0aaHSmXQaSJmnPm5Pmjai3Sm1Qi7Km8ImeUm4KmiSmqmRiUmhTmYJkrSmtJmzSmpUmaOksKmF_d5SmY1VJHkfMmXUmDRmqSmxSmWFjaIkfSmaSm3egaUmvmRmPm6TmGUmcPm5UmsSmEKmmKmnOmoJm1UmkUmMSm0PmWSmQKmbTm3UmZUmmUmnPe3PmjBj1SmbSmOVmaKVDQm6SmIRmDPkLVmFTm4VimRmvjacUmCVmLTm4xhfRmw4hXRmXLkJRmKXg2UmMRmROkNTmqVmyTm96ijRm0EjyRk1LmgRmbQmYRmTLkgVmnQmWKkjVmQob7Qm1VmhVmZLkPNmHoboUmzTm_SmuQmpVm_ZdAPk_zWZBAg6diCjudG9fF_Ae4OPjbKVWmmfRyJkjBIRWmBvRMDPvlEZWmmsR93AYWmdWmgIRbWmuBIlWmyTRfWmwCR1BAlAAiAA"
decoded_data = base64.b64decode(encoded_data).decode('utf-8')

print(decoded_data)
